version: '3.9'

services:
  db:
    image: postgres:15
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb_dt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
